# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestForNavi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry','1.0.1'
  # Pods for TestForNavi

  target 'TestForNaviTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestForNaviUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
