# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestForIGList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestForIGList
  pod 'IGListKit', '~> 3.0'
  target 'TestForIGListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestForIGListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
