# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestForPromise' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TestForPromise
  pod "PromiseKit", "~> 6.0"
  target 'TestForPromiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestForPromiseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
