# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TESTForRAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TESTForRAC

  pod 'ReactiveObjC', '~>3.0.0'

  target 'TESTForRACTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TESTForRACUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
