# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACForSelf' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RACForSelf

	pod 'ReactiveObjC', '3.0.0'

  target 'RACForSelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACForSelfUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
