# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestForAutoLayoutAnimate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry','1.0.1'
  # Pods for TestForAutoLayoutAnimate

  target 'TestForAutoLayoutAnimateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestForAutoLayoutAnimateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
